### PR TITLE
Don't use JUnit internal API

### LINKED ISSUE #1278: ZeebeTestExtension is not working with JUnit Platform Commons 1.11.x
## Description

If JUnit Platform commons 1.10.3 is used, the `ZeebeTestExtension` fails to make a field accessible, because it uses JUnit internal API (`ReflectionUtils`). This internal part of the API is not inteded for external usage. The hard requirement of ZeebeTestExtension is 1.11.x..

The execution results in:

```
java.lang.NoSuchMethodError: 'java.lang.reflect.AccessibleObject org.junit.platform.commons.util.ReflectionUtils.makeAccessible(java.lang.reflect.AccessibleObject)'

	at io.camunda.zeebe.process.test.extension.testcontainer.ZeebeProcessTestExtension.injectField(ZeebeProcessTestExtension.java:162)
	at io.camunda.zeebe.process.test.extension.testcontainer.ZeebeProcessTestExtension.lambda$injectFields$0(ZeebeProcessTestExtension.java:132)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.camunda.zeebe.process.test.extension.testcontainer.ZeebeProcessTestExtension.injectFields(ZeebeProcessTestExtension.java:132)
	at io.camunda.zeebe.process.test.extension.testcontainer.ZeebeProcessTestExtension.beforeEach(ZeebeProcessTestExtension.java:93)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```

This is because:

https://github.com/camunda/zeebe-process-test/blob/bdaa83627690a0ad2c1a8eff4e554e1d0b3a5277/extension/src/main/java/io/camunda/zeebe/process/test/extension/ZeebeProcessTestExtension.java#L162

calls `ReflectionUtils.makeAccessible` method, which is deprecated:

```
	@SuppressWarnings("deprecation") // "AccessibleObject.isAccessible()" is deprecated in Java 9
	public static <T extends AccessibleObject> T makeAccessible(T object) {
		if (!object.isAccessible()) {
			object.setAccessible(true);
		}
		return object;
	}
```

In the same time, the class `ReflectionUtils` declares:

```
/**
 * Collection of utilities for working with the Java reflection APIs.
 *
 * <h2>DISCLAIMER</h2>
 *
 * <p>These utilities are intended solely for usage within the JUnit framework
 * itself. <strong>Any usage by external parties is not supported.</strong>
 * Use at your own risk!
 *
 * <p>Some utilities are published via the maintained {@code ReflectionSupport}
 * class.
 *
 * @since 1.0
 * @see org.junit.platform.commons.support.ReflectionSupport
 */
@API(status = INTERNAL, since = "1.0")
public final class ReflectionUtils {
..
}
```

### Expected behaviour

The `ZeebeTestExtension` is working with any JUnit version

## Environment

JUnit Platform commons 1.10.3
Zeebe-Process-Test 8.6.6

### PR DESCRIPTION
**Pull request by zambrovski**
## Description

- don't use JUnit internal API

## Related issues

closes #1278 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to backport the fix

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually

Documentation:
* [ ] Javadoc has been written
* [ ] The documentation is updated

### CODE REVIEW

**Comment by zambrovski** [comment]
This build is read, but it is read-on-red, since the `main` branch was not building before...

**Review by p-wunderlich — APPROVED** [review]
This PR makes totally sense and looks good. :)

**Review by saig0 — APPROVED** [review]
LGTM. :+1:

**Comment by megglos** [comment]
@zambrovski the main branch builds fine now, can you rebase please?

**Comment by zambrovski** [comment]
Sure, but after new year...

**Comment by zambrovski** [comment]
@megglos I rebased the brnach, but the build is still breaking under macOs (entirely uncorrelated to my change). Please merge, or resolve and merge...

**Comment by megglos** [comment]
The macOS job seems rather flaky recently 😬 Retriggering was enough, I'm glad this will make it still into the upcoming 8.6 patch and 8.7 alpha. Thank you for contributing this!

**Comment by megglos** [comment]
backport failed, likely as this originated from a different repo. Will create the 8.6 PR manually.
