### ISSUE TITLE
Build fails against Zeebe SNAPSHOT

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe-process-test#1166]
## Description

https://github.com/camunda/zeebe-process-test/actions/runs/8842462567/job/24281158599

```
Error:  /home/runner/work/zeebe-process-test/zeebe-process-test/engine/src/main/java/io/camunda/zeebe/process/test/engine/InMemoryLogStorage.java:[63,15] cannot find symbol
  symbol:   method onWriteError(java.lang.Exception)
  location: variable listener of type io.camunda.zeebe.logstreams.storage.LogStorage.AppendListener
```

**Comment by korthout** [comment]
@oleschoenburg I found that this was introduced by https://github.com/camunda/zeebe/commit/07da2501397408369f090b62506351f5852604de

ZPT implements an InMemoryLogStorage, which uses `onWriteError(Exception)`. Reading your commit message I think we can simply remove catching the exception. Do you agree?

https://github.com/camunda/zeebe-process-test/blob/14b62bb27c9adbdf70a7e88cc161fa128cb8c9c1/engine/src/main/java/io/camunda/zeebe/process/test/engine/InMemoryLogStorage.java#L48-L64

**Comment by korthout** [comment]
@megglos I've dragged this into the current iteration as this is blocking ZPT CI and release

**Comment by oleschoenburg** [comment]
> Reading your commit message I think we can simply remove catching the exception. Do you agree?

@korthout Most likey yes. Just go for it IMO.
