### ISSUE TITLE
ZeebeTestExtension is not working with JUnit Platform Commons 1.11.x

### ISSUE THREAD

**Issue by zambrovski** [camunda/zeebe-process-test#1278]
## Description

If JUnit Platform commons 1.10.3 is used, the `ZeebeTestExtension` fails to make a field accessible, because it uses JUnit internal API (`ReflectionUtils`). This internal part of the API is not inteded for external usage. The hard requirement of ZeebeTestExtension is 1.11.x..

The execution results in:

```
java.lang.NoSuchMethodError: 'java.lang.reflect.AccessibleObject org.junit.platform.commons.util.ReflectionUtils.makeAccessible(java.lang.reflect.AccessibleObject)'

	at io.camunda.zeebe.process.test.extension.testcontainer.ZeebeProcessTestExtension.injectField(ZeebeProcessTestExtension.java:162)
	at io.camunda.zeebe.process.test.extension.testcontainer.ZeebeProcessTestExtension.lambda$injectFields$0(ZeebeProcessTestExtension.java:132)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.camunda.zeebe.process.test.extension.testcontainer.ZeebeProcessTestExtension.injectFields(ZeebeProcessTestExtension.java:132)
	at io.camunda.zeebe.process.test.extension.testcontainer.ZeebeProcessTestExtension.beforeEach(ZeebeProcessTestExtension.java:93)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```

This is because:

https://github.com/camunda/zeebe-process-test/blob/bdaa83627690a0ad2c1a8eff4e554e1d0b3a5277/extension/src/main/java/io/camunda/zeebe/process/test/extension/ZeebeProcessTestExtension.java#L162

calls `ReflectionUtils.makeAccessible` method, which is deprecated:

```
	@SuppressWarnings("deprecation") // "AccessibleObject.isAccessible()" is deprecated in Java 9
	public static <T extends AccessibleObject> T makeAccessible(T object) {
		if (!object.isAccessible()) {
			object.setAccessible(true);
		}
		return object;
	}
```

In the same time, the class `ReflectionUtils` declares:

```
/**
 * Collection of utilities for working with the Java reflection APIs.
 *
 * <h2>DISCLAIMER</h2>
 *
 * <p>These utilities are intended solely for usage within the JUnit framework
 * itself. <strong>Any usage by external parties is not supported.</strong>
 * Use at your own risk!
 *
 * <p>Some utilities are published via the maintained {@code ReflectionSupport}
 * class.
 *
 * @since 1.0
 * @see org.junit.platform.commons.support.ReflectionSupport
 */
@API(status = INTERNAL, since = "1.0")
public final class ReflectionUtils {
..
}
```

### Expected behaviour

The `ZeebeTestExtension` is working with any JUnit version

## Environment

JUnit Platform commons 1.10.3
Zeebe-Process-Test 8.6.6

**Comment by zambrovski** [comment]
Sorry, I was confused by the versions. It is still a smell to use internal only API, but I'll close this issue as non-relevant.

**Comment by zambrovski** [comment]
I made a small experiment, checked out the `stable/8.6` branch and replaced the code inside the `ZeebeTestExtension`. Instead of:

```java
private void injectField(
      final ExtensionContext extensionContext, final Field field, final Object object) {
    try {
      ReflectionUtils.makeAccessible(field);
      field.set(extensionContext.getRequiredTestInstance(), object);
    } catch (final IllegalAccessException e) {
      throw new RuntimeException(e);
    }
  }

```

doing plain:

```java
  private void injectField(
      final ExtensionContext extensionContext, final Field field, final Object object) {
    try {
      field.setAccessible(true);
      field.set(extensionContext.getRequiredTestInstance(), object);
    } catch (final IllegalAccessException e) {
      throw new RuntimeException(e);
    }
  }

```

This c  private void injectField(
      final ExtensionContext extensionContext, final Field field, final Object object) {
    try {
      field.setAccessible(true);
      field.set(extensionContext.getRequiredTestInstance(), object);
    } catch (final IllegalAccessException e) {
      throw new RuntimeException(e);
    }
  }
```

I built the resulting library and the bug is gone. Do you want me to create a PR on that? What base branch should I take? Since it is making the 8.6.6 unusable, tell me what base branch you want to use as a base.

Cheers,

Simon

**Comment by saig0** [comment]
@zambrovski great findings. Thank you for sharing. :+1: 

Please create PR with `main` as the base branch. We can backport the PR by adding a label to it. :rocket:

**Comment by aburmeis** [comment]
Really sad, this fix is not included in 8.6.7 - so it is not fixed yet for public
